language: c
before_install:
 - sudo apt-get update
 - sudo apt-get install gperf
 - wget www.tinkerpal.org/sat.tgz -O - | tar xz
compiler:
 - gcc
env:
 - TARGET=frdm_kl25z_gcc_defconfig LIBC_DIR=sat/arm-none-eabi/lib/thumb/cortex-m0 LIBGCC_DIR=sat/lib/gcc/arm-none-eabi/4.7.3/thumb/cortex-m0 CROSS_COMPILE=sat/bin/arm-none-eabi-
script: make $TARGET && make
