language: c
before_install:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update
 - sudo apt-get install gperf
 - sudo apt-get install valgrind
 - sudo apt-get install gcc-arm-none-eabi
 - sudo apt-get install gcc-avr
 - sudo apt-get install avr-libc
 - sudo pip install cpp-coveralls
before_script:
 - arm-none-eabi-gcc --version
compiler:
  - gcc
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "lMbQ+HTmAg9/doSsFNZPdzZy39QYtNc2wgaceFH5rIUXNBb8Z2SSUfiIpx0vjXCrysKSDWMJLuxYfm1Q0kUqg+Pvwcfey74HhbccUdrj/YjSP8wERM3Ue5+s5oAidsSzura96629D0KZbKgLpmvMPRhJ/46DHtBJ1Jwg0xa5T6I="
  matrix:
    - DEFCONFIG=unix_sim_tests_defconfig
addons:
  coverity_scan:
    project:
      name: "ebirger/tinkerpal"
      description: "Build submitted via Travis CI"
    notification_email: tinkerpal.ci@gmail.com
    build_command_prepend: "make $DEFCONFIG"
    build_command:   "make"
    branch_pattern: coverity_scan
script: make $DEFCONFIG && make V=1
