language: c
before_install:
 - sudo apt-get update
 - sudo apt-get install gperf
 - wget www.tinkerpal.org/sat.tgz -O - | tar xz
 - wget www.tinkerpal.org/stellarisware.tgz -O - | tar xz
compiler:
 - gcc
env:
 - BOARD=lm4f120xl_gcc_defconfig STELLARISWARE_DIR=stellarisware LIBC_DIR=sat/arm-none-eabi/lib/thumb/cortex-m4 LIBGCC_DIR=sat/lib/gcc/arm-none-eabi/4.7.3/thumb/cortex-m4 CROSS_COMPILE=sat/bin/arm-none-eabi-
 - BOARD=lm3s6965_gcc_defconfig STELLARISWARE_DIR=stellarisware LIBC_DIR=sat/arm-none-eabi/lib/thumb/cortex-m3 LIBGCC_DIR=sat/lib/gcc/arm-none-eabi/4.7.3/thumb/cortex-m3 CROSS_COMPILE=sat/bin/arm-none-eabi-
script: make $BOARD && make
