language: c
before_install:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update
 - sudo apt-get install gperf
 - sudo apt-get install valgrind
 - sudo apt-get install gcc-arm-none-eabi
 - cd ~ && git clone https://github.com/ebirger/tinkerpal_bsps.git && cd -
before_script:
 - arm-none-eabi-gcc --version
compiler:
  - gcc
env:
  - DEFCONFIG=unix_sim_tests_defconfig
  - DEFCONFIG=frdm_kl25z_gcc_defconfig SKIP_TESTS=1 CROSS_COMPILE=arm-none-eabi-
  - DEFCONFIG=lm4f120xl_gcc_defconfig SKIP_TESTS=1 CROSS_COMPILE=arm-none-eabi- BSPS_DIR=~/tinkerpal_bsps
  - DEFCONFIG=lm3s6918_gcc_defconfig SKIP_TESTS=1 CROSS_COMPILE=arm-none-eabi- BSPS_DIR=~/tinkerpal_bsps
  - DEFCONFIG=lm3s6965_gcc_defconfig SKIP_TESTS=1 CROSS_COMPILE=arm-none-eabi- BSPS_DIR=~/tinkerpal_bsps
  - DEFCONFIG=stm32f3discovery_gcc_defconfig SKIP_TESTS=1 CROSS_COMPILE=arm-none-eabi- BSPS_DIR=~/tinkerpal_bsps
  - DEFCONFIG=stm32f4discovery_gcc_defconfig SKIP_TESTS=1 CROSS_COMPILE=arm-none-eabi- BSPS_DIR=~/tinkerpal_bsps
  - DEFCONFIG=stm32f429idiscovery_gcc_defconfig SKIP_TESTS=1 CROSS_COMPILE=arm-none-eabi- BSPS_DIR=~/tinkerpal_bsps
script: make $DEFCONFIG && make && cd tests && ./run_tests.sh && ./leak_check.sh
