language: c
before_install:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update
 - sudo apt-get install gperf
 - sudo apt-get install valgrind
 - sudo apt-get install gcc-arm-none-eabi
 - cd ~ && git clone https://github.com/ebirger/tinkerpal_bsps.git && cd -
before_script:
 - arm-none-eabi-gcc --version
 - cd ~/tinkerpal_bsps && ls && cd -
compiler:
  - gcc
env:
  - DEFCONFIG=unix_sim_tests_defconfig
  - DEFCONFIG=frdm_kl25z_gcc_defconfig SKIP_TESTS=1 LIBC_DIR=/usr/arm-none-eabi/lib/thumb CROSS_COMPILE=arm-none-eabi-
script: make $DEFCONFIG && make && cd tests && ./run_tests.sh && ./leak_check.sh
