language: c
before_install:
 - sudo apt-get update
 - sudo apt-get install gperf
 - sudo apt-get install valgrind
compiler:
  - gcc
script: make unix_sim_tests_defconfig && make && cd tests && ./run_tests.sh && ./leak_check.sh && cat *.js.lc
