language: c
before_install:
 - sudo apt-get update
 - sudo apt-get install gperf
compiler:
 - gcc
env:
  global:
    - SAT=/home/travis/build/ebirger/tinkerpal/sat
  matrix:
    - BOARD=lm4f120xl_gcc_defconfig STELLARISWARE_DIR=stellarisware LIBC_DIR=sat/arm-none-eabi/lib/thumb/cortex-m4 LIBGCC_DIR=sat/lib/gcc/arm-none-eabi/4.7.3/thumb/cortex-m4 CROSS_COMPILE=$SAT/bin/arm-none-eabi-
    - BOARD=lm3s6965_gcc_defconfig STELLARISWARE_DIR=stellarisware LIBC_DIR=sat/arm-none-eabi/lib/thumb/cortex-m3 LIBGCC_DIR=sat/lib/gcc/arm-none-eabi/4.7.3/thumb/cortex-m3 CROSS_COMPILE=$SAT/bin/arm-none-eabi-
    - BOARD=kl25z_gcc_defconfig LIBC_DIR=sat/arm-none-eabi/lib/thumb/cortex-m0 LIBGCC_DIR=sat/lib/gcc/arm-none-eabi/4.7.3/thumb/cortex-m0 CROSS_COMPILE=$SAT/bin/arm-none-eabi-
script: wget www.tinkerpal.org/sat.tgz -O - | tar xz && wget www.tinkerpal.org/stellarisware.tgz -O - | tar xz && make $BOARD && make V=1
